### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by neamm** [AmyMialeeCommissions/annoyingdifficulty#5] opened 2023-10-13 16:01 UTC
My game crashes when I miss pulling out the "Splinter" from the arm after breaking a log.

![image](https://github.com/AmyMialeeCommissions/annoyingdifficulty/assets/146665856/60a76d8a-f4eb-406f-adf5-2ff418a8674c)

**Comment by AmyMialee** [comment] 2023-10-13 16:06
duplicate of #1

**Closed as completed by AmyMialee** 2023-10-13 16:06 UTC
