### ISSUE TITLE
game crash 

### ISSUE THREAD

**Issue by colejrlol** [AmyMialeeCommissions/annoyingdifficulty#14] opened 2023-10-14 02:11 UTC
game crashes when playing for a minute or loading into a world
[crash-2023-10-13_21.05.31-server.txt](https://github.com/AmyMialeeCommissions/annoyingdifficulty/files/12901369/crash-2023-10-13_21.05.31-server.txt)

**Comment by AmyMialee** [comment] 2023-10-14 10:23
duplicate of #10
install fabric pehkui not forge pehkui

**Closed as not planned** 2023-10-14 10:23 UTC
